# Generated by Django 6.0.4 on 2026-05-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
